const WORD_BANK = [
  { word: "Pizza", category: "Food" },
  { word: "Burger", category: "Food" },
  { word: "Taco", category: "Food" },
  { word: "Sandwich", category: "Food" },
  { word: "Donut", category: "Food" },
  { word: "Ice Cream", category: "Food" },
  { word: "Apple", category: "Food" },
  { word: "Banana", category: "Food" },
  { word: "Cupcake", category: "Food" },
  { word: "Watermelon", category: "Food" },

  { word: "Airplane", category: "Transport" },
  { word: "Car", category: "Transport" },
  { word: "Bus", category: "Transport" },
  { word: "Train", category: "Transport" },
  { word: "Bicycle", category: "Transport" },
  { word: "Motorcycle", category: "Transport" },
  { word: "Boat", category: "Transport" },
  { word: "Helicopter", category: "Transport" },
  { word: "Tractor", category: "Transport" },
  { word: "Submarine", category: "Transport" },

  { word: "Guitar", category: "Music" },
  { word: "Piano", category: "Music" },
  { word: "Drum", category: "Music" },
  { word: "Violin", category: "Music" },
  { word: "Trumpet", category: "Music" },
  { word: "Microphone", category: "Music" },
  { word: "Headphones", category: "Music" },
  { word: "Saxophone", category: "Music" },
  { word: "Harp", category: "Music" },
  { word: "Music Note", category: "Music" },

  { word: "Volcano", category: "Nature" },
  { word: "Mountain", category: "Nature" },
  { word: "River", category: "Nature" },
  { word: "Waterfall", category: "Nature" },
  { word: "Island", category: "Nature" },
  { word: "Cave", category: "Nature" },
  { word: "Desert", category: "Nature" },
  { word: "Ocean", category: "Nature" },
  { word: "Glacier", category: "Nature" },
  { word: "Forest", category: "Nature" },

  { word: "Robot", category: "Technology" },
  { word: "Computer", category: "Technology" },
  { word: "Laptop", category: "Technology" },
  { word: "Smartphone", category: "Technology" },
  { word: "Tablet", category: "Technology" },
  { word: "Keyboard", category: "Technology" },
  { word: "Mouse", category: "Technology" },
  { word: "Television", category: "Technology" },
  { word: "Game Controller", category: "Technology" },
  { word: "Drone", category: "Technology" },

  { word: "Castle", category: "Place" },
  { word: "Beach", category: "Place" },
  { word: "Playground", category: "Place" },
  { word: "Zoo", category: "Place" },
  { word: "Farm", category: "Place" },
  { word: "Airport", category: "Place" },
  { word: "Library", category: "Place" },
  { word: "Museum", category: "Place" },
  { word: "Park", category: "Place" },
  { word: "Circus", category: "Place" },

  { word: "Basketball", category: "Sport" },
  { word: "Soccer Ball", category: "Sport" },
  { word: "Baseball", category: "Sport" },
  { word: "Tennis Racket", category: "Sport" },
  { word: "Football", category: "Sport" },
  { word: "Skateboard", category: "Sport" },
  { word: "Bowling Ball", category: "Sport" },
  { word: "Golf Club", category: "Sport" },
  { word: "Boxing Glove", category: "Sport" },
  { word: "Trophy", category: "Sport" },

  { word: "Umbrella", category: "Object" },
  { word: "Camera", category: "Object" },
  { word: "Clock", category: "Object" },
  { word: "Key", category: "Object" },
  { word: "Candle", category: "Object" },
  { word: "Backpack", category: "Object" },
  { word: "Flashlight", category: "Object" },
  { word: "Magnet", category: "Object" },
  { word: "Ladder", category: "Object" },
  { word: "Paintbrush", category: "Object" },

  { word: "Elephant", category: "Animal" },
  { word: "Lion", category: "Animal" },
  { word: "Tiger", category: "Animal" },
  { word: "Giraffe", category: "Animal" },
  { word: "Monkey", category: "Animal" },
  { word: "Penguin", category: "Animal" },
  { word: "Dolphin", category: "Animal" },
  { word: "Turtle", category: "Animal" },
  { word: "Rabbit", category: "Animal" },
  { word: "Owl", category: "Animal" },

  { word: "Hat", category: "Clothing" },
  { word: "Shoe", category: "Clothing" },
  { word: "Sock", category: "Clothing" },
  { word: "Jacket", category: "Clothing" },
  { word: "Dress", category: "Clothing" },
  { word: "T-Shirt", category: "Clothing" },
  { word: "Scarf", category: "Clothing" },
  { word: "Glove", category: "Clothing" },
  { word: "Belt", category: "Clothing" },
  { word: "Crown", category: "Clothing" },

  { word: "Doctor", category: "Profession" },
  { word: "Chef", category: "Profession" },
  { word: "Firefighter", category: "Profession" },
  { word: "Police Officer", category: "Profession" },
  { word: "Astronaut", category: "Profession" },
  { word: "Teacher", category: "Profession" },
  { word: "Farmer", category: "Profession" },
  { word: "Artist", category: "Profession" },
  { word: "Builder", category: "Profession" },
  { word: "Nurse", category: "Profession" },

  { word: "House", category: "Building" },
  { word: "School", category: "Building" },
  { word: "Hospital", category: "Building" },
  { word: "Church", category: "Building" },
  { word: "Lighthouse", category: "Building" },
  { word: "Windmill", category: "Building" },
  { word: "Factory", category: "Building" },
  { word: "Skyscraper", category: "Building" },
  { word: "Barn", category: "Building" },
  { word: "Igloo", category: "Building" },

  { word: "Sun", category: "Weather" },
  { word: "Cloud", category: "Weather" },
  { word: "Rain", category: "Weather" },
  { word: "Snowflake", category: "Weather" },
  { word: "Lightning", category: "Weather" },
  { word: "Tornado", category: "Weather" },
  { word: "Storm", category: "Weather" },
  { word: "Wind", category: "Weather" },
  { word: "Hail", category: "Weather" },
  { word: "Raindrop", category: "Weather" },

  { word: "Moon", category: "Space" },
  { word: "Star", category: "Space" },
  { word: "Planet", category: "Space" },
  { word: "Saturn", category: "Space" },
  { word: "Comet", category: "Space" },
  { word: "Asteroid", category: "Space" },
  { word: "Spaceship", category: "Space" },
  { word: "Alien", category: "Space" },
  { word: "Telescope", category: "Space" },
  { word: "Galaxy", category: "Space" },

  { word: "Dragon", category: "Fantasy" },
  { word: "Unicorn", category: "Fantasy" },
  { word: "Mermaid", category: "Fantasy" },
  { word: "Wizard", category: "Fantasy" },
  { word: "Fairy", category: "Fantasy" },
  { word: "Monster", category: "Fantasy" },
  { word: "Ghost", category: "Fantasy" },
  { word: "Treasure Chest", category: "Fantasy" },
  { word: "Magic Wand", category: "Fantasy" },
  { word: "Knight", category: "Fantasy" },

  { word: "Pencil", category: "School" },
  { word: "Eraser", category: "School" },
  { word: "Notebook", category: "School" },
  { word: "Ruler", category: "School" },
  { word: "Calculator", category: "School" },
  { word: "Crayon", category: "School" },
  { word: "Book", category: "School" },
  { word: "Globe", category: "School" },
  { word: "Scissors", category: "School" },
  { word: "School Bus", category: "School" },

  { word: "Bed", category: "Home" },
  { word: "Chair", category: "Home" },
  { word: "Table", category: "Home" },
  { word: "Sofa", category: "Home" },
  { word: "Lamp", category: "Home" },
  { word: "Door", category: "Home" },
  { word: "Window", category: "Home" },
  { word: "Bathtub", category: "Home" },
  { word: "Refrigerator", category: "Home" },
  { word: "Teapot", category: "Home" },

  { word: "Teddy Bear", category: "Toy" },
  { word: "Doll", category: "Toy" },
  { word: "Kite", category: "Toy" },
  { word: "Yo-Yo", category: "Toy" },
  { word: "Puzzle", category: "Toy" },
  { word: "Toy Train", category: "Toy" },
  { word: "Balloon", category: "Toy" },
  { word: "Marbles", category: "Toy" },
  { word: "Spinning Top", category: "Toy" },
  { word: "Building Blocks", category: "Toy" },

  { word: "Tree", category: "Plant" },
  { word: "Flower", category: "Plant" },
  { word: "Cactus", category: "Plant" },
  { word: "Mushroom", category: "Plant" },
  { word: "Palm Tree", category: "Plant" },
  { word: "Rose", category: "Plant" },
  { word: "Sunflower", category: "Plant" },
  { word: "Leaf", category: "Plant" },
  { word: "Acorn", category: "Plant" },
  { word: "Pineapple", category: "Plant" },

  { word: "Birthday Cake", category: "Celebration" },
  { word: "Party Hat", category: "Celebration" },
  { word: "Gift", category: "Celebration" },
  { word: "Fireworks", category: "Celebration" },
  { word: "Confetti", category: "Celebration" },
  { word: "Bell", category: "Celebration" },
  { word: "Candy Cane", category: "Celebration" },
  { word: "Pumpkin", category: "Celebration" },
  { word: "Easter Egg", category: "Celebration" },
  { word: "Snow Globe", category: "Celebration" },
];

export { WORD_BANK };
